### ISSUE TITLE
User Story: qpc-tools should have standard argument structure to match other Linux CLIs

### ISSUE THREAD

**Issue by kholdaway** [quipucords/qpc-tools#12]
## Required to transition
- [x] Role Split (PR: https://github.com/quipucords/qpc-tools/pull/21) **Cody**
- [x] Customer install args defined (PR: https://github.com/quipucords/qpc-tools/pull/20)(Kevan)
- [x] Server command implemented to call Ansible (PR: https://github.com/quipucords/qpc-tools/pull/22) **Cody & Kev**
- [x] CLI command implemented to call Ansible (PR: https://github.com/quipucords/qpc-tools/pull/22) **Cody & Kev**
- [x] Convert upstream RPM to python structure **Cody**
- [x] Remove bash script & move the roles. 
- [x] **Kevan working on this:** Update the man page with the new syntax 
- [x] Build downstream RPM based on new upstream structure
- [x] Cut upstream release

## Optional features that would be great
- [x] Improve password input so bash history doesn't contain passwords
- [ ] Improve groups to convey optional/required and maybe offline

**Comment by myersCody** [comment]
The official upstream release has been cut: https://github.com/quipucords/qpc-tools/releases/tag/0.2.0
